version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gremlin-lambda-sample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-auvtsmloyk7l"
s3_prefix = "gremlin-lambda-sample"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
